### Visualize

### Visualize simulation

# ---- Optional: visualization helpers ----
visualize_gamma_grid_static <- function(gamma_fun, n = 25) {
  u <- seq(0, 1, length.out = n)
  v <- seq(0, 1, length.out = n)
  grid <- expand.grid(u = u, v = v)
  UV2  <- gamma_fun(uv=as.matrix(grid))
  df <- data.frame(u = grid$u, v = grid$v, u2 = UV2[,1], v2 = UV2[,2])
  ggplot2::ggplot(df) +
    ggplot2::geom_segment(ggplot2::aes(x = u, y = v, xend = u2, yend = v2),
                          alpha = .6, color = "tomato",
                          arrow = grid::arrow(length = grid::unit(0.08, "cm"))) +
    ggplot2::geom_point(ggplot2::aes(u, v), size = .5, color = "grey40") +
    ggplot2::coord_fixed() + ggplot2::theme_minimal() +
    ggplot2::labs(title = "Gamma warp (boundary-preserving)", x = "u", y = "v")
}


#' Plot the gamma function
#'
#' @param gamma_fun gamma function to plot
#' @param n default=25
#' @param arrow_color default "tomato"
#' @param point_color default "grey40"
#' @param warp_scale default = 1
#' @param uv_grid default = NULL
#'
#' @import ggplot2
#' @export
#'
visualize_gamma_scalar_input <- function(gamma_fun, n = 25,
                                         arrow_color = "tomato",
                                         point_color = "grey40",
                                         warp_scale = 1,uv_grid=NULL) {
  if(is.null(uv_grid)){
    u_seq <- seq(0, 1, length.out = n)
    v_seq <- seq(0, 1, length.out = n)
    uv_grid <- expand.grid(u = u_seq, v = v_seq)
  }


  # 2. input (u,v) to gamma_fun(u, v)
  UV2 <- t(apply(uv_grid, 1, function(uv) gamma_fun(uv[1], uv[2])))
  UV2 <- as.data.frame(UV2)
  names(UV2) <- c("u2", "v2")


  df <- cbind(uv_grid, UV2)
  df$u2 <- df$u + (df$u2 - df$u) * warp_scale
  df$v2 <- df$v + (df$v2 - df$v) * warp_scale

  p <- ggplot2::ggplot(df) +
    ggplot2::geom_segment(
      ggplot2::aes(x = u, y = v, xend = u2, yend = v2),
      alpha = 0.6, color = arrow_color,
      arrow = grid::arrow(length = grid::unit(0.08, "cm"))
    ) +
    ggplot2::geom_point(
      ggplot2::aes(x = u, y = v),
      size = 0.5, color = point_color
    ) +
    ggplot2::coord_fixed() +
    ggplot2::theme_minimal() +
    ggplot2::labs(
      title = "Gamma warp (single-point input)",
      x = "u", y = "v"
    )

  return(p)
}





#library(plotly)

# ==========================================================
# Plot two surfaces (data_list1, data_list2) in 3D
# ==========================================================
#' Plot two surfaces (data_list1, data_list2) in 3D
#'
#' @param data1 generated by generate_surface_data
#' @param data2 generated by generate_surface_data
#' @param color_mode c("uv_hue", "u", "v")
#' @param opacity1 default = 0.7
#' @param opacity2 default = 0.9
#' @param title "Simulated Surfaces (f1 & f2)"
#'
#' @returns a plot
#' @importFrom plotly plot_ly add_markers layout
#' @importFrom magrittr %>%
#' @export
#'
#' @examples
#' data_f1 <- generate_surface_data(f1, 60, 60, noise_sd = 0.01)
#' data_f2 <- generate_surface_data(f2, 60, 60)
#' plot_surface_pair(data_f1, data_f2)
plot_surface_pair <- function(data1, data2,
                              uv_scale = c("global","each"),
                              opacity1 = 0.7,
                              opacity2 = 0.9,
                              title = "Simulated Surfaces (f1 & f2)") {

  require(plotly)
  uv_scale   <- match.arg(uv_scale)

  # --- helper: min-max to [0,1] ---
  to_01 <- function(x) {
    x <- as.numeric(x)
    r <- range(x, na.rm = TRUE)
    if (!is.finite(r[1]) || !is.finite(r[2]) || r[1] == r[2]) {
      return(rep(0.5, length(x)))  # degenerate case: constant / all NA
    }
    (x - r[1]) / (r[2] - r[1])
  }

  # Extract components
  df1 <- cbind(data1$XYZ, data1$UV_grid)
  df2 <- cbind(data2$XYZ, data2$UV_grid)

  # Basic checks (optional but helps debugging)
  if (!all(c("u","v") %in% colnames(df1)) || !all(c("u","v") %in% colnames(df2))) {
    stop("UV_grid must contain columns named 'u' and 'v'.")
  }
  if (!all(c("x","y","z") %in% colnames(df1)) || !all(c("x","y","z") %in% colnames(df2))) {
    stop("XYZ must contain columns named 'x', 'y', 'z'.")
  }

  # --- normalize u,v into [0,1] ---
  if (uv_scale == "each") {
    df1$u01 <- to_01(df1$u); df1$v01 <- to_01(df1$v)
    df2$u01 <- to_01(df2$u); df2$v01 <- to_01(df2$v)
  } else { # global: share the same scaling across both surfaces
    u_all <- c(df1$u, df2$u)
    v_all <- c(df1$v, df2$v)
    u01_all <- to_01(u_all)
    v01_all <- to_01(v_all)
    n1 <- nrow(df1)
    df1$u01 <- u01_all[seq_len(n1)]
    df2$u01 <- u01_all[(n1 + 1):length(u01_all)]
    df1$v01 <- v01_all[seq_len(n1)]
    df2$v01 <- v01_all[(n1 + 1):length(v01_all)]
  }

  # --- define color (use u01/v01) ---
  color1 <- rgb(df1$u01, df1$v01, 1 - df1$u01, maxColorValue = 1)
  color2 <- rgb(df2$u01, df2$v01, 1 - df2$u01, maxColorValue = 1)

  # --- Plotly scatter3D for both surfaces ---
  p <- plot_ly() %>%
    plotly::add_markers(
      data = df1,
      x = ~x, y = ~y, z = ~z,
      color = I(color1),
      marker = list(size = 3, opacity = opacity1),
      name = "Surface f1"
    ) %>%
    plotly::add_markers(
      data = df2,
      x = ~x, y = ~y, z = ~z,
      color = I(color2),
      marker = list(size = 3, opacity = opacity2),
      name = "Surface f2"
    ) %>%
    plotly::layout(
      title = title,
      scene = list(
        xaxis = list(title = "x"),
        yaxis = list(title = "y"),
        zaxis = list(title = "z"),
        aspectmode = "cube"
      ),
      legend = list(bgcolor = "rgba(255,255,255,0.6)")
    )

  return(p)
}

#' Plot a list of surfaces together
#'
#' @param data_list a list of dataset generated by generate_surface_data
#' @param uv_scale c("global","each")
#' @param opacities a vector of values
#' @param legend_labels Surface Name
#' @param marker_size default 3
#' @param title "Simulated Surfaces"
#' @param show_legend TRUE
#' @param legend_bg "rgba(255,255,255,0.6)"
#' @param fix_axis TRUE
#'
#' @returns Surface Plots
#' @export
#'
plot_n_surface <- function(data_list,
                           uv_scale = c("global","each"),
                           opacities = NULL,
                           legend_labels = NULL,
                           marker_size = 3,
                           title = "Simulated Surfaces",
                           show_legend = TRUE,
                           legend_bg = "rgba(255,255,255,0.6)",
                           fix_axis = TRUE) {

  require(plotly)
  uv_scale <- match.arg(uv_scale)

  if (!is.list(data_list) || length(data_list) < 1) {
    stop("data_list must be a non-empty list of surface objects.")
  }
  k <- length(data_list)

  if (is.null(opacities)) opacities <- rep(0.85, k)
  if (length(opacities) != k) stop("Length of opacities must match length(data_list).")

  if (is.null(legend_labels)) {
    legend_labels <- paste0("Surface ", seq_len(k))
  }
  if (length(legend_labels) != k) {
    stop("Length of legend_labels must match length(data_list).")
  }

  to_01 <- function(x) {
    x <- as.numeric(x)
    r <- range(x, na.rm = TRUE)
    if (!is.finite(r[1]) || !is.finite(r[2]) || r[1] == r[2]) {
      return(rep(0.5, length(x)))
    }
    (x - r[1]) / (r[2] - r[1])
  }

  extract_df <- function(data, idx = NA_integer_) {
    if (is.null(data$XYZ) || is.null(data$UV_grid)) {
      stop(sprintf("data_list[[%s]] must contain $XYZ and $UV_grid.", idx))
    }
    df <- cbind(data$XYZ, data$UV_grid)

    if (!all(c("u","v") %in% colnames(df))) {
      stop(sprintf("data_list[[%s]]$UV_grid must have columns 'u' and 'v'.", idx))
    }
    if (!all(c("x","y","z") %in% colnames(df))) {
      stop(sprintf("data_list[[%s]]$XYZ must have columns 'x', 'y', 'z'.", idx))
    }
    df
  }

  dfs <- lapply(seq_len(k), function(i) extract_df(data_list[[i]], i))

  if (uv_scale == "each") {
    dfs <- lapply(dfs, function(df) {
      df$u01 <- to_01(df$u)
      df$v01 <- to_01(df$v)
      df
    })
  } else {
    u_all <- unlist(lapply(dfs, `[[`, "u"), use.names = FALSE)
    v_all <- unlist(lapply(dfs, `[[`, "v"), use.names = FALSE)
    u01_all <- to_01(u_all)
    v01_all <- to_01(v_all)

    lens <- vapply(dfs, nrow, integer(1))
    starts <- c(1L, 1L + cumsum(lens))[seq_len(k)]
    ends <- cumsum(lens)

    for (i in seq_len(k)) {
      dfs[[i]]$u01 <- u01_all[starts[i]:ends[i]]
      dfs[[i]]$v01 <- v01_all[starts[i]:ends[i]]
    }
  }

  make_color <- function(df) {
    rgb(df$u01, df$v01, 1 - df$u01, maxColorValue = 1)
  }
  colors <- lapply(dfs, make_color)

  # fix_axis
  if (fix_axis) {
    x_all <- unlist(lapply(dfs, `[[`, "x"), use.names = FALSE)
    y_all <- unlist(lapply(dfs, `[[`, "y"), use.names = FALSE)
    z_all <- unlist(lapply(dfs, `[[`, "z"), use.names = FALSE)

    x_range_raw <- range(x_all, na.rm = TRUE)
    y_range_raw <- range(y_all, na.rm = TRUE)
    z_range_raw <- range(z_all, na.rm = TRUE)

    x_mid <- mean(x_range_raw)
    y_mid <- mean(y_range_raw)
    z_mid <- mean(z_range_raw)

    max_span <- max(
      diff(x_range_raw),
      diff(y_range_raw),
      diff(z_range_raw)
    )

    x_range <- c(x_mid - max_span/2, x_mid + max_span/2)
    y_range <- c(y_mid - max_span/2, y_mid + max_span/2)
    z_range <- c(z_mid - max_span/2, z_mid + max_span/2)
  }

  p <- plot_ly()

  for (i in seq_len(k)) {
    p <- p %>%
      plotly::add_markers(
        data = dfs[[i]],
        x = ~x, y = ~y, z = ~z,
        color = I(colors[[i]]),
        marker = list(size = marker_size, opacity = opacities[i]),
        name = legend_labels[i],
        showlegend = show_legend
      )
  }

  p <- p %>%
    plotly::layout(
      title = title,
      scene = list(
        xaxis = list(
          title = "x",
          range = if (fix_axis) x_range else NULL,
          autorange = !fix_axis
        ),
        yaxis = list(
          title = "y",
          range = if (fix_axis) y_range else NULL,
          autorange = !fix_axis
        ),
        zaxis = list(
          title = "z",
          range = if (fix_axis) z_range else NULL,
          autorange = !fix_axis
        ),
        aspectmode = "cube"
      ),
      legend = list(bgcolor = legend_bg)
    )

  return(p)
}


#' Plot function for a pme manifold
#'
#' @param df embedding output, a list of points x,y,z
#'
#' @returns get a plot directly
#' @export
#'
#' @examples
#' make_uv_grid <- function(n = 100) {
#'  u <- seq(-1, 2, length.out = n)
#'  v <- seq(-1, 2, length.out = n)
#'  grid <- expand.grid(u = u, v = v)
#'  return(grid)
#' }
#'
#' df_f1 <- evaluate_embedding(make_uv_grid(60), pme1.re$embedding_map)
#' plotly_pointcloud(df_f1)
plotly_pointcloud <- function(df) {
  plot_ly(
    x = df$x,
    y = df$y,
    z = df$z,
    type = "scatter3d",
    mode = "markers",
    marker = list(size = 2, color = df$u)
  )
}


#' Plot pme embedding and original points together
#'
#' @param X_original original points list
#' @param df_embed embedding points list
#' @param title plot title
#'
#' @returns a plot
#'
#' @examples
#' make_uv_grid <- function(n = 100) {
#'  u <- seq(-1, 2, length.out = n)
#'  v <- seq(-1, 2, length.out = n)
#'  grid <- expand.grid(u = u, v = v)
#'  return(grid)
#' }
#'
#' df_f1 <- evaluate_embedding(make_uv_grid(60), pme1.re$embedding_map)
#' plot_pointcloud_pair(X_original = data_f1$XYZ,df_embed = df_f1,"f1")
plot_pointcloud_pair <- function(X_original, df_embed,title=NULL) {

  fig <- plot_ly()

  # 1. original points
  fig <- fig %>%
    add_markers(
      data = as.data.frame(X_original),
      x = ~x, y = ~y, z = ~z,
      marker = list(size = 3, color = "red"),
      name = "Original Data"
    )

  # 2. PME embedding
  fig <- fig %>%
    add_markers(
      x = df_embed$x, y = df_embed$y, z = df_embed$z,
      marker = list(
        size = 2,
        color = df_embed$u,
        colorscale = "Viridis"
      ),
      name = "PME Embedding"
    )

  fig %>% layout(
    scene = list(
      xaxis = list(title = "X"),
      yaxis = list(title = "Y"),
      zaxis = list(title = "Z")
    ),
    title = title
  )
}

