### Visualize

### Visualize simulation

# ---- Optional: visualization helpers ----
visualize_gamma_grid_static <- function(gamma_fun, n = 25) {
  u <- seq(0, 1, length.out = n)
  v <- seq(0, 1, length.out = n)
  grid <- expand.grid(u = u, v = v)
  UV2  <- gamma_fun(uv=as.matrix(grid))
  df <- data.frame(u = grid$u, v = grid$v, u2 = UV2[,1], v2 = UV2[,2])
  ggplot2::ggplot(df) +
    ggplot2::geom_segment(ggplot2::aes(x = u, y = v, xend = u2, yend = v2),
                          alpha = .6, color = "tomato",
                          arrow = grid::arrow(length = grid::unit(0.08, "cm"))) +
    ggplot2::geom_point(ggplot2::aes(u, v), size = .5, color = "grey40") +
    ggplot2::coord_fixed() + ggplot2::theme_minimal() +
    ggplot2::labs(title = "Gamma warp (boundary-preserving)", x = "u", y = "v")
}


#' Plot the gamma function
#'
#' @param gamma_fun gamma function to plot
#' @param n default=25
#' @param arrow_color default "tomato"
#' @param point_color default "grey40"
#' @param warp_scale default = 1
#' @param uv_grid default = NULL
#'
#' @import ggplot2
#' @export
#'
visualize_gamma_scalar_input <- function(gamma_fun, n = 25,
                                         arrow_color = "tomato",
                                         point_color = "grey40",
                                         warp_scale = 1,uv_grid=NULL) {
  if(is.null(uv_grid)){
    u_seq <- seq(0, 1, length.out = n)
    v_seq <- seq(0, 1, length.out = n)
    uv_grid <- expand.grid(u = u_seq, v = v_seq)
  }


  # 2. input (u,v) to gamma_fun(u, v)
  UV2 <- t(apply(uv_grid, 1, function(uv) gamma_fun(uv[1], uv[2])))
  UV2 <- as.data.frame(UV2)
  names(UV2) <- c("u2", "v2")


  df <- cbind(uv_grid, UV2)
  df$u2 <- df$u + (df$u2 - df$u) * warp_scale
  df$v2 <- df$v + (df$v2 - df$v) * warp_scale

  p <- ggplot2::ggplot(df) +
    ggplot2::geom_segment(
      ggplot2::aes(x = u, y = v, xend = u2, yend = v2),
      alpha = 0.6, color = arrow_color,
      arrow = grid::arrow(length = grid::unit(0.08, "cm"))
    ) +
    ggplot2::geom_point(
      ggplot2::aes(x = u, y = v),
      size = 0.5, color = point_color
    ) +
    ggplot2::coord_fixed() +
    ggplot2::theme_minimal() +
    ggplot2::labs(
      title = "Gamma warp (single-point input)",
      x = "u", y = "v"
    )

  return(p)
}





#library(plotly)

# ==========================================================
# Plot two surfaces (data_list1, data_list2) in 3D
# ==========================================================
#' Plot two surfaces (data_list1, data_list2) in 3D
#'
#' @param data1 generated by generate_surface_data
#' @param data2 generated by generate_surface_data
#' @param color_mode c("uv_hue", "u", "v")
#' @param opacity1 default = 0.7
#' @param opacity2 default = 0.9
#' @param title "Simulated Surfaces (f1 & f2)"
#'
#' @returns a plot
#' @importFrom plotly plot_ly add_markers layout
#' @importFrom magrittr %>%
#' @export
#'
#' @examples
#' data_f1 <- generate_surface_data(f1, 60, 60, noise_sd = 0.01)
#' data_f2 <- generate_surface_data(f2, 60, 60)
#' plot_surface_pair(data_f1, data_f2)
plot_surface_pair <- function(data1, data2,
                              color_mode = c("uv_hue", "u", "v"),
                              opacity1 = 0.7,
                              opacity2 = 0.9,
                              title = "Simulated Surfaces (f1 & f2)") {

  color_mode <- match.arg(color_mode)

  # Extract components
  df1 <- cbind(data1$XYZ, data1$UV_grid)
  df2 <- cbind(data2$XYZ, data2$UV_grid)

  # --- define color ---
  if (color_mode == "uv_hue") {
    color1 <- rgb(df1$u, df1$v, 1 - df1$u, maxColorValue = 1)
    color2 <- rgb(df2$u, df2$v, 1 - df2$u, maxColorValue = 1)
  } else if (color_mode == "u") {
    color1 <- df1$u
    color2 <- df2$u
  } else {
    color1 <- df1$v
    color2 <- df2$v
  }

  # --- Plotly scatter3D for both surfaces ---
  p <- plot_ly() %>%
    plotly::add_markers(
      data = df1,
      x = ~x, y = ~y, z = ~z,
      color = I(color1),
      marker = list(size = 3, opacity = opacity1),
      name = "Surface f1"
    ) %>%
    plotly::add_markers(
      data = df2,
      x = ~x, y = ~y, z = ~z,
      color = I(color2),
      marker = list(size = 3, opacity = opacity2),
      name = "Surface f2"
    ) %>%
    plotly::layout(
      title = title,
      scene = list(
        xaxis = list(title = "x"),
        yaxis = list(title = "y"),
        zaxis = list(title = "z"),
        aspectmode = "cube"
      ),
      legend = list(bgcolor = "rgba(255,255,255,0.6)")
    )

  return(p)
}

# ---------------- Example ----------------
# data_f1 <- generate_surface_data(f1, 60, 60, noise_sd = 0.01)
# data_f2 <- generate_surface_data(f2, 60, 60)
# plot_surface_pair(data_f1, data_f2)


plotly_pointcloud <- function(df) {
  plot_ly(
    x = df$x,
    y = df$y,
    z = df$z,
    type = "scatter3d",
    mode = "markers",
    marker = list(size = 2, color = df$u)
  )
}


plot_pointcloud_pair <- function(X_original, df_embed,title=NULL) {

  fig <- plot_ly()

  # 1. original points
  fig <- fig %>%
    add_markers(
      data = as.data.frame(X_original),
      x = ~x, y = ~y, z = ~z,
      marker = list(size = 3, color = "red"),
      name = "Original Data"
    )

  # 2. PME embedding
  fig <- fig %>%
    add_markers(
      x = df_embed$x, y = df_embed$y, z = df_embed$z,
      marker = list(
        size = 2,
        color = df_embed$u,
        colorscale = "Viridis"
      ),
      name = "PME Embedding"
    )

  fig %>% layout(
    scene = list(
      xaxis = list(title = "X"),
      yaxis = list(title = "Y"),
      zaxis = list(title = "Z")
    ),
    title = title
  )
}

